/data/hongcezh/pythonVenv/venv/lib/python3.8/site-packages/torch/autograd/__init__.py:173: UserWarning: Error detected in CudnnRnnBackward0. Traceback of forward call that caused the error:
  File "train_t1.py", line 276, in <module>
    train_loss = train(epoch,subset_graphs,config.batch_size, loss_weight)
  File "train_t1.py", line 73, in train
    prediction = model(data, n_clause, True)
  File "/data/hongcezh/pythonVenv/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/hongcezh/clause-learning/Model2/models.py", line 315, in forward
    prop_feature, _ = self.lstm_clause_update(sv_feature)  # the initial hidden states are set to zero
  File "/data/hongcezh/pythonVenv/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/hongcezh/pythonVenv/venv/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 761, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Epoch: 1, loss: 13299.3438, TP50: 0.001, FP50: 0.008, TN50: 0.958,FN50: 0.033,ACC50: 0.959, max grad: 0.00000:  87%|█████████████████████████████████████▎     | 279/321 [1:01:36<09:16, 13.25s/it]
Traceback (most recent call last):
  File "train_t1.py", line 276, in <module>
    train_loss = train(epoch,subset_graphs,config.batch_size, loss_weight)
  File "train_t1.py", line 105, in train
    loss.backward()
  File "/data/hongcezh/pythonVenv/venv/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/hongcezh/pythonVenv/venv/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'CudnnRnnBackward0' returned nan values in its 0th output.

